### PR TITLE
Misc infra updates

### PR DESCRIPTION
**Pull request by halkeye**
* Record routes on startup for debugging
* Add healthcheck url

### CODE REVIEW

**Review by kwhetstone — APPROVED** [review]
lgtm.  Eventually we can add more useful things to this page like git tag or whatever else would help someone troubleshooting

**Comment by halkeye** [comment]
Yea for sure.

I don't know anything else about spring, while I was researching why the end points came up, this library was suggested for some debugging (there's a way for it to list all endpoints) so i figured it was a simple healthcheck. I do like having useful data in healthchecks/info in general

**Comment by halkeye** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html

**Comment by halkeye** [comment]
omg https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-kubernetes-probes

**Comment by halkeye** [comment]
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-application-info-git specifically covers version numbers

**Pull request merged**
