### PR TITLE
Build everything with docker-compose

### PR DESCRIPTION
**Pull request by sladyn98**
This PR deals with creating the backend without relying on local tools.This has some errors with docker compose which need to be fixed before merging

### CODE REVIEW

**Comment by martinda** [comment]
When I checkout this PR, I get:
```
ocker-compose up -d --build
Building app-server
Step 1/10 : FROM maven:3.5.2-jdk-8-alpine AS MAVEN_BUILD
3.5.2-jdk-8-alpine: Pulling from library/maven
cfc728c1c558: Pull complete
5b12b87f0a0e: Pull complete
b7d6497a92f9: Pull complete
399bf9752347: Pull complete
9e41e7b89fb8: Pull complete
1017f315d511: Pull complete
22bc7fb81913: Pull complete
Digest: sha256:7cebda60f8a541e1bf2330306d22f9786f989187f4ec96539d398a0d4dbfdadb
Status: Downloaded newer image for maven:3.5.2-jdk-8-alpine
 ---> 293423a981a7
Step 2/10 : LABEL maintainer="sladynnunes98@gmail.com"
 ---> Running in 93467273154c
Removing intermediate container 93467273154c
 ---> cc786b81b93e
Step 3/10 : COPY pom.xml /build/
ERROR: Service 'app-server' failed to build: COPY failed: stat /var/lib/docker/tmp/docker-builder778765520/pom.xml: no such file or directory
```

**Comment by sladyn98** [comment]
@martinda Yeah That is the error I am talking about in the description. It cannot find the file to copy even though it should be able to copy everything

**Comment by martinda** [comment]
Then the `.dockerignore` needs to be fixed to allow files to go to the context of what the docker images do need to copy. For example, to reveal the `pom.xml adding this line to the `.dockerignore` works:
```
!**/pom.xml
```

**Comment by martinda** [comment]
What is the goal at the end of this PR? Is it to run just docker commands and no maven commands?

**Comment by sladyn98** [comment]
@martinda Yes the goal is to be able to run without maven because every user might not have maven installed

**Comment by sladyn98** [comment]
@martinda updated docker ignore

**Comment by kwhetstone** [comment]
This should include changes to the readme to run the commands as well.

**Comment by sladyn98** [comment]
This works fine for me and the readme is perfect. No additional commands required

**Pull request merged**
