### PR TITLE
Dynamic modal and plugin

### PR DESCRIPTION
**Pull request by dheerajodha**
**This PR does the following changes:**

- Makes the "Add to configuration" button toggle to and from "Remove from configuration" on clicking it (the change is reflected on the YAML file as well).
- Added a "View Selected Plugins" button to view all the user-selected plugins in a Modal.
- Added a "Clear All" button inside the Modal, which clears the selection of all the currently-selected plugins.

**This PR aims to:**

- Provide feedback to the user about the plugin selection, so they don't have to remember the names of selected plugins.
- Provide the user an option to remove the plugins before reaching the editor, by clicking the "Remove from configuration" button.
- Provide an option to users to give a final glance to all the selected plugins, inside the modal, and also remove them all, if they want to start over.

**This PR solves:**
- #109 
- #139 

**Visual Demo of the changes:**

jenkins

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by sladyn98** [comment]
Would love to have some javscript eyes on this @halkeye

**Comment by halkeye** [comment]
It seems fine to me. Couple things from personal standpoints, but not blockers.

* I am not a fan of mixing css and inline styles, I like using css whenever possible, but otherwise
* {} vs new Object() (no functional difference, just {} is pretty standard these days)

According to the screenshot, the dialog popping up isn't themed the same way as the rest of the side (bootstrap?)  so i'd add the appropriate classes.

but it looks good overall.

**Comment by dheerajodha** [comment]
Hi @halkeye!
Thank you for suggesting these changes, I did all of these changes but before I commit, I wanted to know your views on this little bit modified version of the dialog popup that you pointed out.
I used react-bootstrap now and made the two buttons similar to the rest, but I'm not sure about the background color of the popup/modal, because it is rendered on top of the cards(which already has some dark shades), so IMO we need to give this modal a lighter color which can differentiate it from the cards behind it (I tried light blue, but it looked weird). 

Here's how it looks now:
jenkins_modal

I'm not really good at color combinations so let me know what you think thanks!

**Comment by halkeye** [comment]
> I'm not really good at color combinations so let me know what you think thanks!

yea me neither. I think the contrast works fine. The key thing is to not have people guessing what is or isn't a button, so keeping it consistent is good.

**Review by halkeye — APPROVED** [review]

**Review by sladyn98 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
