### PR TITLE
Replace git.io with expanded URLs

### PR DESCRIPTION
**Pull request by MarkEWaite**

### CODE REVIEW

**Comment by halkeye** [comment]
I can't even see this file used at all

**Comment by MarkEWaite** [comment]
> I can't even see this file used at all

I assumed it was in the test at https://github.com/jenkinsci/custom-distribution-service/blob/a721bfbb26cc8f02035f74527fff117d52a38cb4/src/test/java/com/org/jenkins/custom/jenkins/distribution/service/PluginControllerTest.java#L36

**Comment by halkeye** [comment]
huh, wonder why that didn't show up in search.

to fix the build, we need to set HOME= something, pretty much anything, /tmp, or $WORKSPACE or something

**Comment by MarkEWaite** [comment]
> to fix the build, we need to set HOME= something, pretty much anything, /tmp, or $WORKSPACE or something

I doubt f426cc999c46d8b3489caa89eaed0d89b81b41cf will affect the build, since I don't have commit permission to this repository, but I think that is what you meant when you said that `HOME` needs to be set?

**Comment by halkeye** [comment]
That was my first thought too, but hadn't had a chance to see where exactly the build is failing. 

I think its React Build step. I can do a PR since I do have admin

**Comment by halkeye** [comment]
rebase pls

**Review by halkeye — APPROVED** [review]

**Pull request merged**
