### PR TITLE
Modify Jenkinsfile according to project

### PR DESCRIPTION
**Pull request by sladyn98**
This PR modifies the Jenkinsfile to run a spring boot project and a react project. I am assuming since it is a `mvn` repository the `buildPlugin` step stays the same. I am not too sure about how to run the react project I am assuming we have to add some  pipeline steps to be able to run it.

### CODE REVIEW

**Comment by sladyn98** [comment]
Can we add stages to the pipeline like this
```
stages {
        stage('Build') { 
            steps {
                sh 'npm install' 
            }
        }
    }
```

**Comment by kwhetstone** [comment]
So if we run essentially `mvn test` from the root repository on a multi-module project, each subrepository is built and tested.  So you can add your react tests within the frontend folder and run with your chosen react tester (most likely jest).  When you run `mvn test` locally, do you see the frontend subproject run?

**Comment by kwhetstone** [comment]
Ok, let's try to get the front end building; there's some directions here that you might want to try out: https://medium.com/@itzgeoff/including-react-in-your-spring-boot-maven-build-ae3b8f8826e

**Comment by sladyn98** [comment]
Maybe change the pom.xml group Id to tools.something so that it starts to build

**Comment by sladyn98** [comment]
CC @kwhetstone @LinuxSuRen Gentle reminder to review this :)

**Pull request merged**
