### PR TITLE
Make sure mvn release uses just the version number for tags

### PR DESCRIPTION
**Pull request by halkeye**
cc @timja

### CODE REVIEW

**Review by timja — APPROVED** [review]

**Comment by timja** [comment]
release drafter as well?

**Comment by timja** [comment]
https://github.com/jenkinsci/custom-distribution-service/blob/master/.github/release-drafter.yml#L3

**Comment by halkeye** [comment]
good catch, i'll pull down the branch and make the change

**Review by timja — APPROVED** [review]

**Comment by kwhetstone** [comment]
A weird failure like it's looking for findBugs as a pipeline step.  I'll take a look here once I get some more time.

**Comment by timja** [comment]
findbugs has been removed as it's a deprecated plugin, all plugins were migrated although this was missed because it's special.

it needs to move to warnings-ng instead

**Pull request merged**
